// authActionTypes.js
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';


export const DELETE_COMERCIO_REQUEST = 'DELETE_COMERCIO_REQUEST';
export const DELETE_COMERCIO_SUCCESS = 'DELETE_COMERCIO_SUCCESS';
export const DELETE_COMERCIO_FAILURE = 'DELETE_COMERCIO_FAILURE';

export const UPDATE_COMERCIO_REQUEST = 'UPDATE_COMERCIO_REQUEST';
export const UPDATE_COMERCIO_SUCCESS = 'UPDATE_COMERCIO_SUCCESS';
export const UPDATE_COMERCIO_FAILURE = 'UPDATE_COMERCIO_FAILURE';


export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

// actionTypes.js
export const REGISTER_SERVICE_REQUEST = 'REGISTER_SERVICE_REQUEST';
export const REGISTER_SERVICE_SUCCESS = 'REGISTER_SERVICE_SUCCESS';
export const REGISTER_SERVICE_FAILURE = 'REGISTER_SERVICE_FAILURE';

export const FETCH_CLIENT_SERVICES_REQUEST = 'FETCH_CLIENT_SERVICES_REQUEST';
export const FETCH_CLIENT_SERVICES_SUCCESS = 'FETCH_CLIENT_SERVICES_SUCCESS';
export const FETCH_CLIENT_SERVICES_FAILURE = 'FETCH_CLIENT_SERVICES_FAILURE';

export const FETCH_ALL_SERVICES_REQUEST = 'FETCH_ALL_SERVICES_REQUEST';
export const FETCH_ALL_SERVICES_SUCCESS = 'FETCH_ALL_SERVICES_SUCCESS';
export const FETCH_ALL_SERVICES_FAILURE = 'FETCH_ALL_SERVICES_FAILURE';

export const REGISTER_CLIENT_REQUEST = 'REGISTER_CLIENT_REQUEST';
export const REGISTER_CLIENT_SUCCESS = 'REGISTER_CLIENT_SUCCESS';
export const REGISTER_CLIENT_FAILURE = 'REGISTER_CLIENT_FAILURE';
export const RESET_REGISTER_CLIENT = 'RESET_REGISTER_CLIENT';

export const FETCH_CLIENTS_REQUEST = 'FETCH_CLIENTS_REQUEST';
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';
export const FETCH_CLIENTS_FAIL = 'FETCH_CLIENTS_FAIL';


export const DELETE_CLIENT_REQUEST = 'DELETE_CLIENT_REQUEST';
export const DELETE_CLIENT_SUCCESS = 'DELETE_CLIENT_SUCCESS';
export const DELETE_CLIENT_FAIL = 'DELETE_CLIENT_FAIL';

export const EDIT_CLIENT_REQUEST = 'EDIT_CLIENT_REQUEST';
export const EDIT_CLIENT_SUCCESS = 'EDIT_CLIENT_SUCCESS';
export const EDIT_CLIENT_FAIL = 'EDIT_CLIENT_FAIL';

export const FETCH_COMERCIOS_REQUEST = 'FETCH_COMERCIOS_REQUEST';
export const FETCH_COMERCIOS_SUCCESS = 'FETCH_COMERCIOS_SUCCESS';
export const FETCH_COMERCIOS_FAIL = 'FETCH_COMERCIOS_FAIL';

export const UPDATE_SUBSCRIPTION_REQUEST = 'UPDATE_SUBSCRIPTION_REQUEST';
export const UPDATE_SUBSCRIPTION_SUCCESS = 'UPDATE_SUBSCRIPTION_SUCCESS';
export const UPDATE_SUBSCRIPTION_FAIL = 'UPDATE_SUBSCRIPTION_FAIL';
export const CREATE_SUBSCRIPTION  = 'CREATE_SUBSCRIPTION ';

export const PASSWORD_RESET_EMAIL_SENT = "PASSWORD_RESET_REQUEST_SUCCESS"
export const PASSWORD_RESET_EMAIL_FAILED = "PASSWORD_RESET_REQUEST_FAIL"
